proton: ServiceSpec

pipeline:
  my_sample_pipeline_optional_input: "abcdef"
  my_sample_pipeline_required_input: "uselesschange"

instances:
  - name: "load-test-svc-instance1"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance2"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance3"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance4"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance5"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance6"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance7"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance8"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance9"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance10"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance11"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance12"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance13"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance14"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance15"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance16"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance17"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance18"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"
  - name: "load-test-svc-instance19"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "BAD"
      my_sample_service_instance_required_input: "AWFUL"
  - name: "load-test-svc-instance20"
    environment: "load-test-env"
    spec:
      my_sample_service_instance_optional_input: "thisIsADifferentInstance"
      my_sample_service_instance_required_input: "ThisInstanceIsNew"